# IT情報
- name: gigazine
  url: "https://gigazine.net/news/rss_atom/"
  fetch_content: true
  instruction: |
    'it,gigazine'タグをつけて
- name: hackernews
  url: "https://news.ycombinator.com/rss"
  fetch_content: true
  instructions: |
    'it,hackernewsタグをつけて'
- name: infoq
  url: "https://www.infoq.com/feed/"
  fetch_content: true
  instructions: |
    'it,infoq'タグをつけて
- name: zenn
  url: "https://zenn.dev/feed"
  fetch_content: true
  instructions: |
    'it,zenn'タグをつけて

# 政治経済
- name: bloomberg
  url: "https://feeds.bloomberg.com/markets/news.rss"
  fetch_content: true
  instruction: |
    'economics,bloomberg'タグをつけて
- name: bbc
  url: "http://feeds.bbci.co.uk/news/world/rss.xml"
  fetch_content: true
  instruction: |
    'economics,bbc'タグをつけて
